name: [Sample] Sync Theme
on:
  repository_dispatch:
    types: [themes/update]
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm add -g @shopify/cli@latest

      - name: Pull Live Theme
        env:
          SHOPIFY_STORE: "emma-dev"
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          cd theme
          shopify theme pull \
            --store "$SHOPIFY_STORE" \
            --password "$SHOPIFY_TOKEN" \
            -l
      - name: Commit and push if theme changed
        run: |
          cd theme
          git config user.name = "Shopify Bot"
          git config user.email = "shopify-bot@emma-sleep.com"
          
          if [[ -z $(git status) ]]; then
            echo "âœ…No theme changes detected."
            exit 0
          fi
          
          git add -A
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "(bot): Sync LIVE theme at ${timestamp}"
          git push

